### ISSUE TITLE
Is there a better way to deal with corrupted .oims files?

### ISSUE THREAD

**Issue by jaycedowell** [lwa-project/orville_wideband_imager#30]
Orville at North Arm occasionally has a problem with .oims file corruption when there is a power outage.  This isn't necessarily a big problem but it does lead to cases like today where Orville has to be restarted because of:
```
lwana-orville bash[2177]: Exception in thread Thread-7:
lwana-orville bash[2177]: Traceback (most recent call last):
lwana-orville bash[2177]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
lwana-orville bash[2177]:     self.run()
lwana-orville bash[2177]:   File "/usr/lib/python3.8/threading.py", line 870, in run
lwana-orville bash[2177]:     self._target(*self._args, **self._kwargs)
lwana-orville bash[2177]:   File "/home/jdowell/orville3/orville_imager.py", line 1451, in main
lwana-orville bash[2177]:     self._save_archive_image(self.station, time_tag, ihdr, arc_freq, arc_data)
lwana-orville bash[2177]:   File "/home/jdowell/orville3/orville_imager.py", line 1327, in _save_archive_image
lwana-orville bash[2177]:     db = OrvilleImageDB(outname, mode='a', station=station.name)
lwana-orville bash[2177]:   File "/usr/local/lib/python3.8/dist-packages/lsl_toolkits/OrvilleImage/OrvilleImageDB.py", line 247, in __init__
lwana-orville bash[2177]:     raise RuntimeError('The file "%s" appears to be '
lwana-orville bash[2177]: RuntimeError: The file "/data/orville/archive/60548/60548_190000_33.161MHz_49.431MHz.oims" appears to be corrupted.
```
We should probably try to catch this so that the imager doesn't die.

**Comment by jaycedowell** [comment]
Those two commit will keep images flowing to LWATV until the UTC hour changes and a new file starts.

**Comment by jaycedowell** [comment]
It would be great if we could recover from a corrupted file but this will work for now.
